### ISSUE TITLE
Create the repo and skeleton for the following services

### ISSUE THREAD

**Issue by linsun** [cf-furnace/cf-furnace#2]
- [x] k8s-stager
- [x] k8s-cc-uploader
- [x] k8s-nsync
- [x] K8s-tps
- [ ] Route-Emitter

Follow up work of the swagger doc

**Comment by jandubois** [comment]
This work is done, with the exception of the route emitter, which doesn't have an HTTP API.  Implementation of the route emitter is covered by #7.
